# Predict command
## COMMAND: [ python, predict.py ]
# Train command
TRAIN_COMMAND: [ python, train.py ]
LOO_CV_COMMAND: [python, loo_cross_validation.py]

CLASSES:
  - { label: 1,  name: 'lying',                             }
  - { label: 2,  name: 'sitting',                             }
  - { label: 3,  name: 'standing',                 }
  - { label: 4,  name: 'walking',        }
  - { label: 5,  name: 'running',       }
  - { label: 6,  name: 'cycling',                            }
  - { label: 7,  name: 'nordic walking',                             }
  - { label: 12, name: 'ascending stairs',                               }
  - { label: 13, name: 'descending stairs',                       }
  - { label: 16, name: 'vacuum cleaning',           }
  - { label: 17, name: 'ironing',  }
  - { label: 24, name: 'rope jumping',}

# --- Information about data
# Path to training dataset 
TRAIN_DATA: data/pamap2/

# Amount of training data used for validation (between 0 and 1)
VALID_SPLIT: 0.2
# Randomly selected test subjects (Not used during LOSO!)
TEST_SUBJECTS: null
SEED: 28
FOLDS: 5

NUM_WORKERS: 10  # Num of workers for data loading
NUM_GPUS: [0]  # How many GPUs to use
WANDB: False
WANDB_KEY: '<Put wandb key here>'


DATASET: PAMAP2
DATASET_ARGS:
  x_columns: [[38, 39, 40]]  # ankle x,y,z accelerometer
  y_column: [1]
  padding_val: [0.0]
  # 50==1sec ==> 3000==60sec==1min
  sequence_length: [15000]  # Window size (in samples) fed into the model
  normalize: [True]  # Whether to normalize the training data
  norm_params_path: [params/norm_params/HUNT4_T/normalization_params_STFT_feats78_seqlen599/]
  n_fft: [50]  # Size of Fourier transform (in samples)
  phase: [False]
  hop_length: [null]  # For STFT computation. If None, n_fft//2
  source_freq: [100]  # Sampling frequency of dataset
  target_freq: [50]  # Sampling frequency to use for training
  reorientation: [True]  # Reorient axes to be closer to HUNT4 orientation

# -- Model 
# Which classifier to use 
ALGORITHM: DownstreamMLP
# Arguments for classifier
# (all given as lists in case to perform a GridSearch)
ALGORITHM_ARGS:
  epochs: [50]
  batch_size: [1]
  loss: [CrossEntropyLoss]
  optimizer: [Adam]
  weight_decay: [0.0]
  output_activation: [softmax]
  metrics: [[F1Score,Accuracy,Precision,Recall]]  # Which metrics to log
  lr: [2e-4]
  lr_scheduler: [ExponentialTFDecay]
  # Architecture params
  upstream_algorithm: [TransformerEncoderNetwork]
  upstream_model_path: [params/MonoSelfPAB_upstream/upstream_model.ckpt]
  rmv_upstream_layers: [4]  # remove the last 4 layers: 3metrics+1pred heads
  weighted_sum_layer: [null]  # None=no weighted sum
  fine_tune_step: [0.75]  # when start fine tune in %
  dropout: [0.1]  # Dropout probability
  n_prediction_head_layers: [2]  # Num layers of MLP at end of model
  dim_prediction_head: [1028]  # Dim of hidden layers of MLP at end od model


STORE_CMATS: True  # Store test cmats on disk
SKIP_FINISHED_ARGS: False

# Metric which defines the best model
EVAL_METRIC: average_f1score
